site_name: HA-Pen
pages:
- [index.md, Home]
- [install.md, Installation]
- [config.md, Configuring the system]
- [sockets.md, Sockets]
- [timers.md, Timers]
- [usage.md, Using the system]
theme: readthedocs
